spring:
  application:
    name: shoutreview

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoutreview
    username: postgres
    password: 1008

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: <EMAIL>
    password: <PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

authority:
  admin: admin


